steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'wordpress:test', './dockerfile/.']
  timeout: 500s

- name: 'gcr.io/cloud-builders/docker'
  args: ['docker','tag','wordpress:test','gcr.io/ttc-team-03/wordpress:test']

- name: 'gcr.io/cloud-builders/docker'
  args: ['docker','push', 'gcr.io/ttc-team-03/wordpress:test']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['kubectl', 'apply', '-f', './3.wordpress-statefulset.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast3-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ttcteam'
tags:
  - wordpress
images: ['gcr.io/ttc-team-03/wordpress:latest']