steps:
- name: 'gcr.io/ttc-team-03/wordpress:latest'
  args: ['build', '-t', 'wordpress:test', './web/.']
  timeout: 500s
- name: 'test'
  args: ['docker','tag','wordpress:test','gcr.io/ttc-team-03/wordpress:test']
- name: 'gcr.io/ttc-team-03/wordpress:test'
  args: ['docker','push', 'gcr.io/ttc-team-03/wordpress:test']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/my-deployment', 'my-container=gcr.io/ttc-team-03/wordpress:latest']
#- name: 'Kubernetes Deployment'
#  args: ['kubectl','apply','-f','./wordpress/3.wordpress-statefulset.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast3-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ttcteam'
tags:
  - wordpress
images: ['gcr.io/ttc-team-03/wordpress:latest']