apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
  namespace: ttc-team-03
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: wordpress
  minReplicas: 3
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory 
      targetAverageUtilization: 70
