apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: elasticsearch-hpa
  namespace: ttc-team-03
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: elasticsearch
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory 
      targetAverageUtilization: 70