apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa2
  namespace: ttc-team-03
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: statefulset
    name: wordpress
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50